plugins {
    id "com.android.application" version "8.3.0" apply false
    id "com.android.library" version "8.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.8.22" apply false
}

rootProject.buildDir = '../build'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
rootProject.name = "Aerobasket"
include ":app"